// Code generated by MockGen. DO NOT EDIT.
// Source: ../repo/seat_repo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/quangdnptit/booking-be/models"
)

// MockSeatRepo is a mock of SeatRepo interface.
type MockSeatRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSeatRepoMockRecorder
}

// MockSeatRepoMockRecorder is the mock recorder for MockSeatRepo.
type MockSeatRepoMockRecorder struct {
	mock *MockSeatRepo
}

// NewMockSeatRepo creates a new mock instance.
func NewMockSeatRepo(ctrl *gomock.Controller) *MockSeatRepo {
	mock := &MockSeatRepo{ctrl: ctrl}
	mock.recorder = &MockSeatRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatRepo) EXPECT() *MockSeatRepoMockRecorder {
	return m.recorder
}

// GenerateSeats mocks base method.
func (m *MockSeatRepo) GenerateSeats(ctx context.Context, seats []models.Seat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSeats", ctx, seats)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateSeats indicates an expected call of GenerateSeats.
func (mr *MockSeatRepoMockRecorder) GenerateSeats(ctx, seats interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSeats", reflect.TypeOf((*MockSeatRepo)(nil).GenerateSeats), ctx, seats)
}

// GetByShowtimeID mocks base method.
func (m *MockSeatRepo) GetByShowtimeID(ctx context.Context, showtimeID string) ([]models.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShowtimeID", ctx, showtimeID)
	ret0, _ := ret[0].([]models.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShowtimeID indicates an expected call of GetByShowtimeID.
func (mr *MockSeatRepoMockRecorder) GetByShowtimeID(ctx, showtimeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShowtimeID", reflect.TypeOf((*MockSeatRepo)(nil).GetByShowtimeID), ctx, showtimeID)
}

// GetByShowtimeIDAndSeatKeys mocks base method.
func (m *MockSeatRepo) GetByShowtimeIDAndSeatKeys(ctx context.Context, showtimeID string, seatKeys []string) ([]models.Seat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShowtimeIDAndSeatKeys", ctx, showtimeID, seatKeys)
	ret0, _ := ret[0].([]models.Seat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShowtimeIDAndSeatKeys indicates an expected call of GetByShowtimeIDAndSeatKeys.
func (mr *MockSeatRepoMockRecorder) GetByShowtimeIDAndSeatKeys(ctx, showtimeID, seatKeys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShowtimeIDAndSeatKeys", reflect.TypeOf((*MockSeatRepo)(nil).GetByShowtimeIDAndSeatKeys), ctx, showtimeID, seatKeys)
}

// Update mocks base method.
func (m *MockSeatRepo) Update(ctx context.Context, seat models.Seat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, seat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSeatRepoMockRecorder) Update(ctx, seat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSeatRepo)(nil).Update), ctx, seat)
}

// UpdateStatusByKey mocks base method.
func (m *MockSeatRepo) UpdateStatusByKey(ctx context.Context, showtimeID, seatKey, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByKey", ctx, showtimeID, seatKey, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusByKey indicates an expected call of UpdateStatusByKey.
func (mr *MockSeatRepoMockRecorder) UpdateStatusByKey(ctx, showtimeID, seatKey, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByKey", reflect.TypeOf((*MockSeatRepo)(nil).UpdateStatusByKey), ctx, showtimeID, seatKey, status)
}
